local dap = require("dap")
vim.keymap.set("n", "<F5>", function()
	dap.continue()
end)
vim.keymap.set("n", "<F10>", function()
	dap.step_over()
end)
vim.keymap.set("n", "<F11>", function()
	dap.step_into()
end)
vim.keymap.set("n", "<F12>", function()
	dap.step_out()
end)
vim.keymap.set("n", "<Leader>b", function()
	dap.toggle_breakpoint()
end)

local dap_widgets = require("dap.ui.widgets")
vim.keymap.set({ "n", "v" }, "<Leader>dh", function()
	dap_widgets.hover()
end)
vim.keymap.set({ "n", "v" }, "<Leader>dp", function()
	dap_widgets.preview()
end)
vim.keymap.set("n", "<Leader>df", function()
	dap_widgets.centered_float(dap_widgets.frames)
end)
vim.keymap.set("n", "<Leader>ds", function()
	dap_widgets.centered_float(dap_widgets.scopes)
end)
